server:
  port: 8002
spring:
  application:
    name: yigou-product
  datasource:  #数据库的配置
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yigou_product?useUnicode=true&characterEncoding=UTF-8  #防止中文乱码
    username: root
    password: 112233
mybatis-plus:
  mapper-locations: classpath:tx/yigou/mapper/*Mapper.xml #扫mapper映射
  type-aliases-package: tx.yigou.domain,tx.yigou.query  #别名的配置
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    prefer-ip-address: true
