server:
  port: 8002
spring:
  application:
    name: product-provider
  datasource:  #数据库的配置
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yigou_product?useUnicode=true&characterEncoding=UTF-8  #防止中文乱码
    username: root
    password: 112233
eureka:
  client:
    service-url:
      defaultZone: http://www.eureka-7001.com:7001/eureka  #告诉服务提供者要把服务注册到哪儿 #单机环境
  instance:
    prefer-ip-address: true #显示客户端真实ip
mybatis-plus:
  mapper-locations: classpath:tx/yigou/mapper/*Mapper.xml #扫mapper映射
  type-aliases-package: tx.yigou.domain,tx.yigou.query  #别名的配置
